### ISSUE TITLE
Port searching and sorting examples Python 3.7

### ISSUE THREAD

**Issue by bt3gl** [bt3gl/Book-on-Python-Algorithms-and-Data-Structures#21]

**Comment by EmadMokhtar** [comment]
Can you elaborate more on what need to be done? I can pick this one for Hacktober Feast

**Comment by bt3gl** [comment]
@EmadMokhtar I am starting to rewrite the book in Python 3.7
So this task would be: create a similar directory [here](https://github.com/bt3gl/Book-Python_and_Algorithms/tree/master/Second_edition_2019), and port (some or all) searching and sorting code to python 3.7.
